/// Repository dimension for the 5 demo applications.
table Dim_Repository
	lineageTag: 9706c910-e2d4-44f6-99b8-1982511327c2

	column RepositoryKey
		dataType: int64
		formatString: 0
		lineageTag: c135ff3b-ffc2-40dd-bd7e-e8ef599a7c62
		summarizeBy: none
		sourceColumn: RepositoryKey

		annotation SummarizationSetBy = Automatic

	column RepositoryName
		dataType: string
		lineageTag: 1920d310-966a-431c-b200-88f744b0ff54
		summarizeBy: none
		sourceColumn: RepositoryName

		annotation SummarizationSetBy = Automatic

	column TechStack
		dataType: string
		lineageTag: f3560818-6d58-4998-b1bf-927b39cd06a2
		summarizeBy: none
		sourceColumn: TechStack

		annotation SummarizationSetBy = Automatic

	column PrimaryEngine
		dataType: string
		lineageTag: b95adb41-5d38-470e-94c7-4b42ebc329d1
		summarizeBy: none
		sourceColumn: PrimaryEngine

		annotation SummarizationSetBy = Automatic

	partition Dim_Repository = m
		mode: import
		source =
				let
					Source = Table.FromRows(
						{
							{1, "apm-demo-app-001", "Node.js / TypeScript", "Semantic Scanner"},
							{2, "apm-demo-app-002", "Python", "Unicode Scanner"},
							{3, "apm-demo-app-003", ".NET / C#", "MCP Validator"},
							{4, "apm-demo-app-004", "Java / Spring", "Lockfile Auditor"},
							{5, "apm-demo-app-005", "Multi-stack", "All Engines"}
						},
						type table [RepositoryKey = Int64.Type, RepositoryName = text, TechStack = text, PrimaryEngine = text]
					)
				in
					Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

